### ISSUE TITLE
build problems on debian 9.4 stretch 

### ISSUE THREAD

**Issue by karlkashofer** [iustin/corydalis#4] opened 2019-08-24 16:55 UTC
I try to build on debian, it fails with:
```
karl@mediaserver:~/corydalis$ stack build
Specified file "git-version" for extra-source-files does not exist
Building all executables for corydalis once. After a successful build of all of them, only specified executables will be rebuilt.
Warning: Dependent file listed in:
         /home/karl/corydalis/corydalis/.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/Settings/Development.hi
         does not exist: git-version

Warning: File listed in corydalis/corydalis.cabal file does not exist: git-version

````
If i provide a dummy file (git --version > git-version) it still fails somewhere else:
```
karl@mediaserver:~/corydalis$ stack build
Building all executables for `corydalis' once. After a successful build of all of them, only specified executables will be rebuilt.
corydalis> build (lib + exe)
Preprocessing library for corydalis-0.4.0..
Building library for corydalis-0.4.0..
[32 of 32] Compiling Application
/home/karl/corydalis/corydalis/src/Application.hs:1:1: fatal:
    cannot find object file ‘.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/Indexer.dyn_o’
    while linking an interpreted expression

--  While building package corydalis-0.4.0 using:
      /home/karl/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 build lib:corydalis exe:corydalis exe:db-util exe:scanner --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
karl@mediaserver:~/corydalis$ 

```
Any idea what could be wrong ?
Cheers,
KK

**Comment by iustin** [comment] 2019-08-28 20:27
1. For the git-version, you can/should generate it via "make git-version".

2. For the stack build error, that is weird. Which version of stack do you have?

**Comment by karlkashofer** [comment] 2019-08-29 10:41
Hi !

Thanks for your help !

1.) making git-version works, maybe add that to the build instructions ? Error #2 still the same though.
2.) $ stack --version
Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2

**Comment by karlkashofer** [comment] 2019-08-30 11:56
Hi !

After a "stack clean --full" the project has now built without incident ! 
Maybe my fake git-version file messed something up.
Thanks,
KK

**Comment by iustin** [comment] 2019-09-03 21:26
OK, I must admit I don't know stack enough to understand why a clean was needed. I'll update the docs to mention the make git-version, but that text file is not interpreted by anything, so I doubt it was the cause. Thanks!

**Comment by iustin** [comment] 2023-11-04 21:05
Closing this since it's very old. I still don't know if this works for other people, or if anyone cares, but… :)

**Closed as completed by iustin** 2023-11-04 21:05 UTC
